# ----------------------------------- Load Balancer
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   namespace: metallb-system
#   name: config
# data:
#   config: |
#     address-pools:
#     - name: default
#       protocol: layer2
#       addresses:
#       - 192.168.99.199/32
# ...
# ----------------------------------- Nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:kubed
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
...
# ----------------------------------- Wordpress
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       containers:
#       - name: wordpress
#         image: wordpress:kubed
#         ports:
#         - name: wordpress
#           containerPort: 5050
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: wordpress
# spec:
#   ports:
#   - name: wordpress
#     port: 5050
#     protocol: TCP
#     targetPort: 5050
#   selector:
#     app: wordpress
#   type: LoadBalancer
# ...
