apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:kubed
        imagePullPolicy: Never
        ports:
        - name: ftp
          containerPort: 2142
        - name: ftps
          containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip-key
spec:
  ports:
  - name: ftp
    port: 2142
    protocol: TCP
    targetPort: 2142
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer
