apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pv-claim
spec:
  storageClassName: influx-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
spec:
  selector:
    matchLabels:
      app: influx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influx
    spec:
      volumes:
      - name: influx-volume
        persistentVolumeClaim:
          claimName: influx-pv-claim
      containers:
      - name: influx
        image: influx:kubed
        ports:
        - containerPort: 8086
          name: influx
        volumeMounts:
        - name: influx-volume
          mountPath: /var/lib/influx
---
apiVersion: v1
kind: Service
metadata:
  name: influx
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip-key
spec:
  type: LoadBalancer
  selector:
    app: influx
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
