apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:kubed
        ports:
        - name: phpmyadmin
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: share-ip-key
spec:
  loadBalancerIP: 192.168.99.21
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
