apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:kubed
        ports:
        - name: wordpress
          containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
